POST http://localhost:3000/api/person HTTP/1.1
content-type: application/json

{
  "name": "Sample Person",
  "email": "sample@person.com",
  "phone": "42999362757",
  "$connect": {
    "teams": [ 1, 5, 7 ]
  }
}

#####
GET http://localhost:3000/api/person HTTP/1.1
content-type: application/json

###### 
GET http://localhost:3000/api/person/5 HTTP/1.1
content-type: application/json

#####
DELETE http://localhost:3000/api/person/5 HTTP/1.1
content-type: application/json

#####
PUT http://localhost:3000/api/person/2 HTTP/1.1
content-type: application/json

{
  "name": "Bruh",

  "$connect": {
    "team": [ 1 ]
  }
}