POST http://localhost:3000/api/team HTTP/1.1
content-type: application/json

{
  "name": "Alou"
}

#####
GET http://localhost:3000/api/team HTTP/1.1
content-type: application/json

###### 
@target = 1

GET http://localhost:3000/api/team/{{target}} HTTP/1.1
content-type: application/json

#####
DELETE http://localhost:3000/api/team/{{target}} HTTP/1.1
content-type: application/json

#####
PUT http://localhost:3000/api/team/{{target}} HTTP/1.1
content-type: application/json

{
  "name": "teste",
  
  "$connect": {
    "persons": [ 1 ]
  }
}