POST http://localhost:3000/api/team HTTP/1.1
content-type: application/json

{
  "name": "Team Test",
  "member": [ "1hFyzCcAJkgupLMs", "NuX3vyAV7VLztbUI" ]
}

#####
GET http://localhost:3000/api/team HTTP/1.1
content-type: application/json

###### 
@target = 9GFoTQ9b4WiiPUqR

GET http://localhost:3000/api/team/{{target}} HTTP/1.1
content-type: application/json

#####
DELETE http://localhost:3000/api/team/{{target}} HTTP/1.1
content-type: application/json

#####
PUT http://localhost:3000/api/team/{{target}} HTTP/1.1
content-type: application/json

{
  "name": "teste",
  "$add": {
    "member": "XQsxjn6UfsQlMVQu"
  },
  "$remove": {
    "member": "1hFyzCcAJkgupLMs" 
  }
}